### ISSUE TITLE
Installation issue (linux + conda) - pydot cannot find graphviz binaries

### ISSUE THREAD

**Issue by scribby182** [rldm/hw3-tester#15]
Not sure how common this issue is, but just in case someone else hits it.  After getting pygraphviz to install properly, when actually running the tester I hit this error:
`b'Warning: Could not load "...anaconda3/envs/hw3_tester_36/lib/graphviz/libgvplugin_pango.so.6" - file not found\nWarning: Could not load "...anaconda3/envs/hw3_tester_36/lib/graphviz/libgvplugin_pango.so.6" - file not found\nFormat: "png" not recognized. Use one of: canon cmap cmapx cmapx_np dot dot_json eps fig gv imap imap_np ismap json json0 mp pdf pic plain plain-ext png pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4 xdot_json\n'`

This was solved by the following:
    conda install -c conda-forge xorg-libxrender xorg-libxpm

No idea why, but that fix worked.

**Comment by mimoralea** [comment]
Can you add a note to the README to include this? I rather this in the README, than here...
