### ISSUE TITLE
graphviz needs to be installed seperately on the OS

### ISSUE THREAD

**Issue by giladgressel** [rldm/hw3-tester#2]
`pip install pygraphviz` will fail if you don't have graphviz installed.

There are a few SO queries about this.
I have mac osx and use homebrew, this one worked for me.

https://stackoverflow.com/a/44208667

I had to use the `--install-option` bits as well

@mimoralea  you may want to update the readme to include some note about this.

**Comment by mimoralea** [comment]
Would you be able to propose a fix to the REAME?

**Comment by giladgressel** [comment]
ya, I will make a pull request later today. I had started one but I wasn't sure how to word it, how verbose to be etc. I think I will just make a link to this issue (and we can keep it open) as a thread for troubleshooting.
MY guess is solutions for this are going to vary a lot.
I had a bit of trouble getting it to work, I tried 3 or 4 things before I got it go.

**Comment by addisonhuddy** [comment]
To everyone running into this problem on ubuntu, make sure you have python3-dev installed.  I didn't know there was a different python-dev for 2 and 3.  https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory.

**Comment by mimoralea** [comment]
If you have suggestions for a particular OS, feel free to add a line to the README and create a pull request.
